export enum UserTypes {
    ADMIN = "ADMIN",
    COMPANY_OWNER = "COMPANY_OWNER",
    localadmin = 'add action, add control',
    PERSONELL = "PERSONEL",
    GUEST = "GUEST",
    DEMO = "DEMO"
}

export enum AppUserActions {
    ADD_LAW = "ADD_LAW",
    EDIT_LAW = "EDIT_LAW",
    VIEW_LAW = "VIEW_LAW",
    DELETE_LAW = "DELETE_LAW",
    ADD_ACTIONS = "ADD_ACTIONS",
    EDIT_ACTIONS = "EDIT_ACTIONS",
    VIEW_ACTIONS = "VIEW_ACTIONS",
    DELETE_ACTIONS = "DELETE_ACTIONS",
    ADD_CONTROL = "ADD_CONTROL",
    EDIT_CONTROL = "EDIT_CONTROL",
    VIEW_CONTROL = "VIEW_CONTROL",
    DELETE_CONTROL = "DELETE_CONTROL",
    ADD_COMPANY = "ADD_COMPANY",
    EDIT_COMPANY = "EDIT_COMPANY",
    VIEW_COMPANY = "VIEW_COMPANY",
    DELETE_COMPANY = "DELETE_COMPANY",
    VIEW_STATISTICS = "VIEW_STATISTICS",
    PERFORM_ASSESSMENT = "PERFORM_ASSESSMENT",
    ADD_PERSONNEL = "ADD_PERSONNEL",
    EDIT_PERSONNEL = "EDIT_PERSONNEL",
    VIEW_PERSONNEL = "VIEW_PERSONNEL",
    DELETE_PERSONNEL = "DELETE_PERSONNEL",
    VIEW_SUBSCRIPTION = "VIEW_SUBSCRIPTION"
}

//  -> can only view