name: Deploy Zenou frontend to server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: npm install

      - name: Prepare production build for Zenou
        run: |
          npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "./build/*"
          target: "/var/www/html/application-bootstrap/frontend"