name: Deploy Zenou frontend to server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOYMENT_PAT }}
      
      - name: Set up Git credentials
        env:
          PAT: ${{ secrets.DEPLOYMENT_PAT }}
        run: |
          git config --global user.email "kambangsinclaire@gmail.com"
          git config --global user.name "Kambang Sinclaire"
          git config --global credential.helper store
          git remote set-url origin https://github.com/Zenou-Ecosystem/zenou-ui.git

      - name: Setting up SSH keys
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Deploying repo changes to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/frontend
            git pull origin main
            npm install && npm run build