name: Deploy Zenou frontend to server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOYMENT_PAT }}

      - name: Setting up SSH keys
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Deploying repo changes to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/application-bootstrap/frontend
            git pull origin main
            npm run build